/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type SupportedNssaiAvailabilityData struct {

	Tai *Tai `json:"tai"`

	SupportedSnssaiList []Snssai `json:"supportedSnssaiList"`
}

func (s *SupportedNssaiAvailabilityData) CheckIntegrity() error {
    if s.Tai == nil {
        return fmt.Errorf("`tai` in request body should not be empty")
    } else {
        err := s.Tai.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("`tai`:%s", err.Error())
        }
    }

    if s.SupportedSnssaiList == nil || len(s.SupportedSnssaiList) == 0 {
        return fmt.Errorf("`supportedSnssaiList` in request body should not be empty")
    } else {
        for i, snssai := range s.SupportedSnssaiList {
            err := snssai.CheckIntegrity()
            if err != nil {
                return fmt.Errorf("`supportedSnssaiList`[%d]:%s", i, err.Error())
            }
        }
    }

    return nil
}
