/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type RoamingIndication string

// List of RoamingIndication
const (
	NON_ROAMINGRoamingIndication RoamingIndication = "NON_ROAMING"
	LOCAL_BREAKOUTRoamingIndication RoamingIndication = "LOCAL_BREAKOUT"
	HOME_ROUTED_ROAMINGRoamingIndication RoamingIndication = "HOME_ROUTED_ROAMING"
)

func (r *RoamingIndication) CheckIntegrity() error {
    if *r != NON_ROAMINGRoamingIndication && *r != LOCAL_BREAKOUTRoamingIndication &&
       *r != HOME_ROUTED_ROAMINGRoamingIndication {
        return fmt.Errorf("'%s' is unrecognized", string(*r))
    }

    return nil
}
