/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type AccessType string

// List of AccessType
const (
	AccessType__3_GPP_ACCESS AccessType = "3GPP_ACCESS"
	AccessType_NON_3_GPP_ACCESS AccessType = "NON_3GPP_ACCESS"
)

func (a *AccessType) CheckIntegrity() error {
    if *a != AccessType__3_GPP_ACCESS && *a != AccessType_NON_3_GPP_ACCESS {
        return fmt.Errorf("'%s' is unrecognized", string(*a))
    }

    return nil
}
