/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type SliceInfoForPduSession struct {

	SNssai *Snssai `json:"sNssai"`

	RoamingIndication *RoamingIndication `json:"roamingIndication"`

	HomeSnssai *Snssai `json:"homeSnssai,omitempty"`
}
