/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type MappingOfSnssai struct {

    ServingSnssai *Snssai `json:"servingSnssai" yaml:"servingSnssai"`

    HomeSnssai *Snssai `json:"homeSnssai" yaml:"homeSnssai"`
}

func (m *MappingOfSnssai) CheckIntegrity() error {
    if m.ServingSnssai == nil {
        return fmt.Errorf("`servingSnssai` in query parameter should not be empty")
    } else {
        err := m.ServingSnssai.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("`servingSnssai`:%s", err.Error())
        }
    }

    if m.HomeSnssai == nil {
        return fmt.Errorf("`homeSnssai` in query parameter should not be empty")
    } else {
        err := m.HomeSnssai.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("`homeSnssai`:%s", err.Error())
        }
    }

    return nil
}
