/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type ConfiguredSnssai struct {

	ConfiguredSnssai *Snssai `json:"configuredSnssai"`

	MappedHomeSnssai *Snssai `json:"mappedHomeSnssai,omitempty"`
}

func (c *ConfiguredSnssai) CheckIntegrity() error {
    if c.ConfiguredSnssai == nil {
        return fmt.Errorf("`configuredSnssai` in query parameter should not be empty")
    } else {
        err := c.ConfiguredSnssai.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("`configuredSnssai`:%s", err.Error())
        }
    }

    if c.MappedHomeSnssai != nil {
        err := c.MappedHomeSnssai.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("`mappedHomeSnssai`:%s", err.Error())
        }
    }

    return nil
}
