/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type SupportedNssaiAvailabilityData struct {

	Tai *Tai `json:"tai"`

	SupportedSnssaiList []Snssai `json:"supportedSnssaiList"`
}
