/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type AuthorizedNssaiAvailabilityInfo struct {

	AuthorizedNssaiAvailabilityData []AuthorizedNssaiAvailabilityData `json:"authorizedNssaiAvailabilityData"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`
}

func (a *AuthorizedNssaiAvailabilityInfo) Sort() {
    var byTai ByTai = a.AuthorizedNssaiAvailabilityData
    byTai.Sort()
}
