/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type NfType string

// List of NFType
const (
        NfType_NRF NfType = "NRF"
        NfType_UDM NfType = "UDM"
        NfType_AMF NfType = "AMF"
        NfType_SMF NfType = "SMF"
        NfType_AUSF NfType = "AUSF"
        NfType_NEF NfType = "NEF"
        NfType_PCF NfType = "PCF"
        NfType_SMSF NfType = "SMSF"
        NfType_NSSF NfType = "NSSF"
        NfType_UDR NfType = "UDR"
        NfType_LMF NfType = "LMF"
        NfType_GMLC NfType = "GMLC"
        NfType__5_G_EIR NfType = "5G_EIR"
        NfType_SEPP NfType = "SEPP"
        NfType_UPF NfType = "UPF"
        NfType_N3_IWF NfType = "N3IWF"
        NfType_AF NfType = "AF"
        NfType_UDSF NfType = "UDSF"
        NfType_BSF NfType = "BSF"
        NfType_CHF NfType = "CHF"
        NfType_NWDAF NfType = "NWDAF"
)

func (n NfType) CheckIntegrity() error {
    if n != NfType_NRF && n != NfType_UDM && n != NfType_AMF && n != NfType_SMF && n != NfType_AUSF &&
       n != NfType_NEF && n != NfType_PCF && n != NfType_SMSF && n != NfType_NSSF && n != NfType_UDR &&
       n != NfType_LMF && n != NfType_GMLC && n != NfType__5_G_EIR && n != NfType_SEPP && n != NfType_UPF &&
       n != NfType_N3_IWF && n != NfType_AF && n != NfType_UDSF && n != NfType_BSF && n != NfType_CHF &&
       n != NfType_NWDAF {
        return fmt.Errorf("'%s' is unrecognized", string(n))
    }

    return nil
}
