/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "sort"
)

type AuthorizedNetworkSliceInfo struct {

	AllowedNssaiList []AllowedNssai `json:"allowedNssaiList,omitempty"`

	ConfiguredNssai []ConfiguredSnssai `json:"configuredNssai,omitempty"`

	TargetAmfSet string `json:"targetAmfSet,omitempty"`

	CandidateAmfList []string `json:"candidateAmfList,omitempty"`

	RejectedNssaiInPlmn []Snssai `json:"rejectedNssaiInPlmn,omitempty"`

	RejectedNssaiInTa []Snssai `json:"rejectedNssaiInTa,omitempty"`

	NsiInformation *NsiInformation `json:"nsiInformation,omitempty"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	NrfAmfSet string `json:"nrfAmfSet,omitempty"`
}

func (a *AuthorizedNetworkSliceInfo) Sort() {
    var byAccessType ByAccessType = a.AllowedNssaiList
    byAccessType.Sort()

    sort.Sort(ByConfiguredSnssai(a.ConfiguredNssai))
    sort.Strings(a.CandidateAmfList)
    sort.Sort(BySst(a.RejectedNssaiInPlmn))
    sort.Sort(BySst(a.RejectedNssaiInTa))
}
