/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type PatchDocument []PatchItem

func (p *PatchDocument) CheckIntegrity() error {
    for i, patchItem := range *p {
        err := patchItem.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("[%d]:%s", i, err.Error())
        }
    }

    return nil
}
