/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type PatchItem struct {

	Op *PatchOperation `json:"op"`

	Path string `json:"path"`

	From string `json:"from,omitempty"`

	Value *map[string]interface{} `json:"value,omitempty"`
}

func (p *PatchItem) CheckIntegrity() error {
    if p.Op == nil {
        return fmt.Errorf("`op` should not be empty")
    } else {
        err := p.Op.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("`op`:%s", err.Error())
        }
    }

    if p.Path == "" {
        return fmt.Errorf("`path` should not be empty")
    }

    return nil
}
