/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"time"
)

type NssfEventSubscriptionCreateData struct {

	NfNssaiAvailabilityUri string `json:"nfNssaiAvailabilityUri"`

	TaiList []Tai `json:"taiList"`

	Event *NssfEventType `json:"event"`

	Expiry time.Time `json:"expiry,omitempty"`
}
