/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type PatchOperation string

// List of PatchOperation
const (
    PatchOperation_ADD PatchOperation = "add"
    PatchOperation_COPY PatchOperation = "copy"
    PatchOperation_MOVE PatchOperation = "move"
    PatchOperation_REMOVE PatchOperation = "remove"
    PatchOperation_REPLACE PatchOperation = "replace"
    PatchOperation_TEST PatchOperation = "test"
)

func (p *PatchOperation) CheckIntegrity() error {
    if *p != PatchOperation_ADD && *p != PatchOperation_COPY && *p != PatchOperation_MOVE &&
       *p != PatchOperation_REMOVE && *p != PatchOperation_REPLACE && *p != PatchOperation_TEST {
           return fmt.Errorf("'%s' is unrecognized", string(*p))
    }

    return nil
}
