/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type NfType string

// List of NFType
const (
	NRF NfType = "NRF"
	UDM NfType = "UDM"
	AMF NfType = "AMF"
	SMF NfType = "SMF"
	AUSF NfType = "AUSF"
	NEF NfType = "NEF"
	PCF NfType = "PCF"
	SMSF NfType = "SMSF"
	NSSF NfType = "NSSF"
	UDR NfType = "UDR"
	LMF NfType = "LMF"
	GMLC NfType = "GMLC"
	_5_G_EIR NfType = "5G_EIR"
	SEPP NfType = "SEPP"
	UPF NfType = "UPF"
	N3_IWF NfType = "N3IWF"
	AF NfType = "AF"
	UDSF NfType = "UDSF"
	BSF NfType = "BSF"
	CHF NfType = "CHF"
	NWDAF NfType = "NWDAF"
)

func (n NfType) CheckIntegrity() error {
    if n != NRF && n != UDM && n != AMF && n != SMF && n != AUSF && n != NEF && n != PCF && n != SMSF && n != NSSF &&
       n != UDR && n != LMF && n != GMLC && n != _5_G_EIR && n != SEPP && n != UPF && n != N3_IWF && n != AF &&
       n != UDSF && n != BSF && n != CHF && n != NWDAF {
        return fmt.Errorf("'%s' is unrecognized", string(n))
    }

    return nil
}
