/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type Snssai struct {

    Sst int32 `json:"sst" yaml:"sst"`

    Sd string `json:"sd,omitempty" yaml:"sd,omitempty"`
}

func (s *Snssai) CheckIntegrity() error {
    if s.Sst == 0 {
        return fmt.Errorf("`sst` should not be empty")
    }

    return nil
}

type BySst []Snssai

func (s BySst) Len() int {
    return len(s)
}

func (s BySst) Swap(i, j int) {
    s[i], s[j] = s[j], s[i]
}

func (s BySst) Less(i, j int) bool {
    if s[i].Sst == s[j].Sst {
        return s[i].Sd < s[j].Sd
    }
    return s[i].Sst < s[j].Sst
}
