/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
    "fmt"
)

type Tai struct {

    PlmnId *PlmnId `json:"plmnId" yaml:"plmnId"`

    Tac string `json:"tac" yaml:"tac"`
}

func (t *Tai) CheckIntegrity() error {
    if t.PlmnId == nil {
        return fmt.Errorf("`plmnId` in query parameter should not be empty")
    } else {
        err := t.PlmnId.CheckIntegrity()
        if err != nil {
            return fmt.Errorf("`plmnId`:%s", err.Error())
        }
    }

    if t.Tac == "" {
        return fmt.Errorf("`tac` in query parameter should not be empty")
    }

    return nil
}
