/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
    "net/http"

    factory "./factory"
    flog "./flog"
    nssf "./nssf"
)

func main() {
    factory.InitConfigFactory("./conf/nssf_config.yaml")
    flog.InitLog(string(*factory.NssfConfig.Info.Service), true)
    flog.Infof("Server started")

    router := nssf.NewRouter()

    flog.Fatal(http.ListenAndServe(":8080", router))
}
