/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
    "github.com/gin-gonic/gin"

    "./factory"
    "./flog"
    "./nsselection"
    "./nssaiavailability"
)

func main() {
    factory.InitConfigFactory("./conf/nssf_config.yaml")
    flog.System.Infof("Server started")

    // Running in "release" mode instead of "debug" mode
    gin.SetMode(gin.ReleaseMode)
    router := gin.Default()

    nsselection.AddService(router)
    nssaiavailability.AddService(router)

    flog.System.Fatal(router.Run(":8080"))
}
