info:
  service: Nnssf_NSSelection
  version: 1.0.0
  title: NSSF NS Selection
  description: NSSF Network Slice Selection Service
  url: http://140.113.194.229:8080/nnssf-nsselection/v1

configuration:
  supportedNssaiInPlmn:
    - sst: 1
      sd: 1
    - sst: 1
      sd: 2
    - sst: 1
      sd: 3
    - sst: 2
      sd: 1
    - sst: 2
      sd: 2
  amfList:
    - nfId: ffa2e8d7-3275-49c7-8631-6af1df1d9d26
      supportedSnssai:
        - sst: 1
          sd: 1
        - sst: 1
          sd: 2
        - sst: 2
          sd: 1
    - nfId: 0e8831c3-6286-4689-ab27-1e2161e15cb1
      supportedSnssai:
        - sst: 1
          sd: 1
        - sst: 1
          sd: 2
        - sst: 1
          sd: 3
        - sst: 2
        - sd: 1
    - nfId: a1fba9ba-2e39-4e22-9c74-f749da571d0d
      supportedSnssai:
        - sst: 1
          sd: 1
        - sst: 1
          sd: 3
        - sst: 2
          sd: 1
  taList:
    - tac: 33456
      supportedSnssai:
        - sst: 1
          sd: 1
        - sst: 1
          sd: 2
    - tac: 33457
      supportedSnssai:
        - sst: 1
          sd: 1
        - sst: 1
          sd: 2
    - tac: 33458
      supportedSnssai:
        - sst: 1
          sd: 1
        - sst: 1
          sd: 3
    - tac: 33459
      supportedSnssai:
        - sst: 1
          sd: 1
        - sst: 2
          sd: 1
  mappingListFromPlmn:
    - operatorName: NTT Docomo
      homePlmnId:
        mcc: 440
        mnc: 10
      mappingOfSnssai:
        - servingSnssai:
            sst: 1
            sd: 1
          homeSnssai:
            sst: 1
            sd: 1
        - servingSnssai:
            sst: 1
            sd: 2
          homeSnssai:
            sst: 1
            sd: 3
        - servingSnssai:
            sst: 1
            sd: 3
          homeSnssai:
            sst: 1
            sd: 4
        - servingSnssai:
            sst: 2
            sd: 1
          homeSnssai:
            sst: 2
            sd: 2
    - operatorName: AT&T Mobility
      homePlmnId:
        mcc: 310
        mnc: 560
      mappingOfSnssai:
        - servingSnssai:
            sst: 1
            sd: 1
          homeSnssai:
            sst: 1
            sd: 2
        - servingSnssai:
            sst: 1
            sd: 2
          homeSnssai:
            sst: 1
            sd: 3
