/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nssaiavailability

import (
	"net/http"
    "strings"

    "github.com/gin-gonic/gin"

    "../flog"
    . "../model"
    "../util"
)

// NSSAIAvailabilityPost - Creates subscriptions for notification about updates to NSSAI availability information
func NSSAIAvailabilityPost(c *gin.Context) {

    flog.Nssaiavailability.Infof("Request received - NSSAIAvailabilityPost")

    var (
        isValidRequest bool = true
        status int
        n NssfEventSubscriptionCreateData
        s NssfEventSubscriptionCreatedData
        d ProblemDetails
    )

    // Parse request body
    err := c.BindJSON(&n)
    if err != nil {
        problemDetail := "[Request Body] " + err.Error()
        status = http.StatusBadRequest
        d = ProblemDetails {
            Title: util.MALFORMED_REQUEST,
            Status: http.StatusBadRequest,
            Detail: problemDetail,
        }
        isValidRequest = false
    }

    // Check data integrity
    err = n.CheckIntegrity()
    if err != nil {
        problemDetail := "[Request Body] " + err.Error()
        s := strings.Split(problemDetail, "`")
        invalidParam := s[len(s) - 2]
        status = http.StatusBadRequest
        d = ProblemDetails {
            Title: util.INVALID_REQUEST,
            Status: http.StatusBadRequest,
            Detail: problemDetail,
            InvalidParams: []InvalidParam {
                {
                    Param: invalidParam,
                    Reason: problemDetail,
                },
            },
        }
        isValidRequest = false
    }

    // TODO: If NF consumer is not authorized to update NSSAI availability, return ProblemDetails with code 403 Forbidden

    if isValidRequest == true {
        status = subscriptionPost(n, &s, &d)
    }

    // Set response
    switch status {
        case http.StatusCreated:
            c.JSON(status, s)
            flog.Nssaiavailability.Infof("Response code 201 Created")
        case http.StatusBadRequest:
            c.JSON(status, d)
            flog.Nssaiavailability.Infof(d.Detail)
            flog.Nssaiavailability.Infof("Response code 400 Bad Request")
        case http.StatusForbidden:
            c.JSON(status, d)
            flog.Nssaiavailability.Infof(d.Detail)
            flog.Nssaiavailability.Infof("Response code 403 Forbidden")
        default:
            flog.Nssaiavailability.Warnf("Unknown response code")
    }
}
