/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nssaiavailability

import (
	"net/http"

    "github.com/gin-gonic/gin"

    "../flog"
    . "../model"
)

// NSSAIAvailabilityUnsubscribe - Deletes an already existing NSSAI availability notification subscription
func NSSAIAvailabilityUnsubscribe(c *gin.Context) {

    flog.Nssaiavailability.Infof("Request received - NSSAIAvailabilityUnsubscribe")

    var (
        subscriptionId string
        status int
        d ProblemDetails
    )

    // Due to conflict of route matching, 'subscriptions' in the route is replaced with the existing wildcard ':nfId'
    nfId := c.Param("nfId")
    if nfId != "subscriptions" {
        c.JSON(http.StatusNotFound, gin.H{})
        flog.Nssaiavailability.Infof("404 Not Found")
        return
    }
    // Parse subscriptionId from URL path
    subscriptionId = c.Param("subscriptionId")

    status = subscriptionDelete(subscriptionId, &d)

    // Set response
    switch status {
    case http.StatusNoContent:
        c.JSON(status, gin.H{})
        flog.Nssaiavailability.Infof("Response code 204 No Content")
    case http.StatusNotFound:
        c.JSON(status, d)
        flog.Nssaiavailability.Infof(d.Detail)
        flog.Nssaiavailability.Infof("Response code 404 Not Found")
    default:
        flog.Nssaiavailability.Warnf("Unknown reponse code")
    }
}
