/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nssaiavailability

import (
	"net/http"

    "github.com/gin-gonic/gin"

    "free5gc-nssf/flog"
    . "free5gc-nssf/model"
    "free5gc-nssf/nssf_handler/nssf_message"
)

// NSSAIAvailabilityUnsubscribe - Deletes an already existing NSSAI availability notification subscription
func NSSAIAvailabilityUnsubscribe(httpChannel chan nssf_message.HttpResponseMessage, c *gin.Context) {

    flog.Nssaiavailability.Infof("Request received - NSSAIAvailabilityUnsubscribe")

    var (
        subscriptionId string
        status int
        d ProblemDetails
    )

    // Parse subscriptionId from URL path
    subscriptionId = c.Param("subscriptionId")

    status = subscriptionDelete(subscriptionId, &d)

    // Set response
    switch status {
    case http.StatusNoContent:
        var arg interface{}
        nssf_message.SendHttpResponseMessage(httpChannel, nssf_message.HttpResponseMessageResponse, arg)
        flog.Nssaiavailability.Infof("Response code 204 No Content")
    case http.StatusNotFound:
        nssf_message.SendHttpResponseMessage(httpChannel, nssf_message.HttpResponseMessageProblemDetails, d)
        flog.Nssaiavailability.Infof(d.Detail)
        flog.Nssaiavailability.Infof("Response code 404 Not Found")
    default:
        flog.Nssaiavailability.Warnf("Unknown reponse code")
    }
}
