/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nssf

import (
    "encoding/json"
	"net/http"

    "github.com/gorilla/mux"

    flog "../flog"
    . "../model"
)

// NSSAIAvailabilityUnsubscribe - Deletes an already existing NSSAI availability notification subscription
func NSSAIAvailabilityUnsubscribe(w http.ResponseWriter, r *http.Request) {

    flog.Nssaiavailability.Infof("Request received - NSSAIAvailabilityUnsubscribe")

    var (
        subscriptionId string
        status int
        d ProblemDetails
    )

    // Parse subscriptionId from URL path
    vars := mux.Vars(r)
    subscriptionId = vars["subscriptionId"]

    status = subscriptionDelete(subscriptionId, &d)

    // Set response
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	w.WriteHeader(status)
    switch status {
    case http.StatusNoContent:
        flog.Nssaiavailability.Infof("Response code 204 No Content")
    case http.StatusNotFound:
        json.NewEncoder(w).Encode(&d)
        flog.Nssaiavailability.Infof(d.Detail)
        flog.Nssaiavailability.Infof("Response code 404 Not Found")
    default:
        flog.Nssaiavailability.Warnf("Unknown reponse code")
    }
}
