/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"

	. "free5gc-nssf/model"
	"free5gc-nssf/nssf_handler"
	"free5gc-nssf/nssf_handler/nssf_message"
)

func ApiSubscriptionsCollection(c *gin.Context) {
	channelMsg := nssf_message.NewHttpChannelMessage()
	channelMsg.Event = nssf_message.EventNSSAIAvailabilityPost
	channelMsg.Context = c

	nssf_handler.SendMessage(channelMsg)
	rcvMsg := <-channelMsg.HttpChannel

	switch rcvMsg.Type {
	case nssf_message.HttpResponseMessageResponse:
		response := rcvMsg.Response.(NssfEventSubscriptionCreatedData)
		c.JSON(http.StatusCreated, response)
	case nssf_message.HttpResponseMessageProblemDetails:
		response := rcvMsg.Response.(ProblemDetails)
		c.JSON(int(response.Status), response)
	}
}
